<?php
loadPartial('header'); ?>
<div class="content">
  i am contact and I am from views
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam ratione veritatis aliquid, sed dignissimos modi temporibus accusamus iste aut explicabo voluptatum odit harum natus, libero vel voluptatibus! Nihil cumque optio illum magni ratione rem doloremque qui. Ratione animi est fugit vel perspiciatis obcaecati, eveniet, nulla, quasi eius mollitia asperiores minima? Non, dolore. Eos atque voluptates ullam earum labore perferendis nemo ut vitae, consequatur, quisquam dolorum porro recusandae, repellat et facilis harum optio quasi id fugit? Nisi eos, quas similique id eveniet maiores earum tempore beatae repudiandae dolorem temporibus accusantium quis mollitia fugit nesciunt libero debitis voluptate a magnam deleniti ipsam, nobis corporis! Libero quos, nobis magni nulla reprehenderit in eum culpa ipsum facilis laborum voluptatum dolorem odio accusantium nesciunt delectus iure molestias illum maiores laudantium porro deserunt. A cumque possimus ut beatae mollitia. Aut sed autem voluptatibus quam, sapiente sequi ipsam accusantium enim reprehenderit nihil esse aperiam iste omnis. Illo, recusandae! Voluptate aspernatur velit enim nesciunt minima necessitatibus molestias quibusdam voluptas? Exercitationem itaque dolores veniam nesciunt nam? Velit placeat quaerat repudiandae aut officia corporis? Ad in, autem aut sunt vel officiis sed excepturi, debitis doloremque dolorum tempora! Quae ipsam et blanditiis, amet ad, velit magnam similique minus id ratione, cumque odio. In temporibus a et ab itaque suscipit quas explicabo eum qui veritatis laboriosam nesciunt eius dignissimos soluta, at veniam molestiae illum, odio quidem possimus voluptatem, velit nihil accusamus. Itaque eius asperiores, voluptatum suscipit veniam, ab, velit architecto praesentium assumenda ipsam aspernatur a exercitationem ad ullam reprehenderit? Atque amet unde neque sint enim illum rem culpa, at quibusdam iusto. Reiciendis doloribus laborum cumque nemo at necessitatibus voluptatum quos rem deserunt eius? Obcaecati esse suscipit odio illum odit fugiat iusto, quam sequi dolorum, eos eveniet quisquam quas eaque iure at! Dolore at esse, explicabo officiis corrupti
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta animi optio tenetur sint quasi corporis culpa veritatis officia eius eligendi atque minus enim repellat aliquam, voluptatem molestiae consequuntur nobis nostrum tempora officiis praesentium sequi obcaecati? Praesentium magni illo vitae earum dolore, provident laboriosam, repellendus repellat molestias similique a tempore possimus eum ducimus natus facilis, saepe quisquam officia? Rerum quidem voluptatibus, laborum deleniti minima, adipisci perferendis id est odio ut at totam similique maiores iste, autem mollitia modi quibusdam! Natus soluta tenetur eveniet dolore corrupti beatae, quaerat id. Unde perspiciatis ratione eos aperiam neque at ducimus tempore quos alias laudantium accusamus consequuntur aspernatur porro consequatur, asperiores explicabo! Quis nobis expedita eos maiores adipisci modi corporis autem alias repellendus dolore dolorum voluptates, nemo, quia repudiandae ex molestiae at aperiam aspernatur a corrupti ipsa consequatur doloremque laborum? Praesentium laudantium debitis rem laborum facere delectus eligendi velit illo quidem dicta cumque aliquid quae atque voluptatibus ratione esse nihil adipisci maiores temporibus eveniet rerum quam necessitatibus, dolore voluptates? Aliquid culpa quisquam sed dicta dolorum doloribus libero consequatur minima perspiciatis cumque quos laboriosam saepe quis vitae sit accusamus quam, cum, obcaecati explicabo recusandae necessitatibus. Praesentium consectetur itaque ab, totam quibusdam iure eveniet asperiores iste ad delectus repudiandae, rem provident laborum soluta exercitationem dolorum esse, necessitatibus vero accusamus odit. Qui saepe amet laborum dolore aperiam error dicta, voluptatibus odio. Perferendis, obcaecati accusantium. Fuga expedita alias laudantium aut corporis, vero minus? Neque animi asperiores autem sequi praesentium iusto ipsa ipsam ad illum, mollitia eligendi commodi expedita similique fugit illo a at odit obcaecati ullam, molestias voluptate cumque, consectetur consequatur optio? Praesentium facilis sequi delectus, deleniti sapiente earum nulla culpa sed. Maiores eius, assumenda vero velit omnis accusamus quidem totam voluptas iusto consectetur suscipit ab, provident et expedita quos! Quos, et distinctio! Veniam vitae sit quis ipsum inventore! Sed. obcaecati atque molestiae reprehenderit dolorem.</p>
</div>
<?php
loadPartial('footer');
